export const FETCH_INVITATIONRECEIVE_REQUEST = "FETCH_INVITATIONRECEIVE_REQUEST"
export const FETCH_INVITATIONRECEIVE_SUCCESS = "FETCH_INVITATIONRECEIVE_SUCCESS"
export const FETCH_INVITATIONRECEIVE_FAILURE = "FETCH_INVITATIONRECEIVE_FAILURE"
export const FETCH_USERID = "FETCH_USERID"