export const FETCH_INVITATIONSENT_REQUEST = "FETCH_INVITATIONSENT_REQUEST"
export const FETCH_INVITATIONSENT_SUCCESS = "FETCH_INVITATIONSENT_SUCCESS"
export const FETCH_INVITATIONSENT_FAILURE = "FETCH_INVITATIONSENT_FAILURE"